# CSV file with single column, patient, with every patient ID
patients: patients.csv 
# CSV file with info on each sample/read group
units: units.csv
# Sequencing Type
# For whole exome, specify WES
# For whole genome, specify WGS
# If you have both WES and WGS samples, process them separately with 2 versions of this pipeline
# This is needed as the data types require different computational resources and genomic regions to interrogate
sequencing_type: WES

# SLURM Log File
# Set directory to save slurm log files (if using cluster execution)
# This can be an absolute or relative path
# If the directory doesn't exist the pipeline will create it
slurm_log_dir: slurm-logs


# Genomic Regions
# Uncompressed BED (.bed) file with regions for variant calling. Must be specified!
# For WES data, coverage is evaluated based on reads in these regions
# For WGS data, coverage is evaluated across the genome in 500 bp windows
genomic_regions: /data/Storage_DAS03/home3/menteeD/dna/WES_snakemake/KBPMA_WES-master/data/SureSelectV4_covered.bed

# Reference genome sources
# Directory where reference fasta and supporting files are stored
ref_dir: /data/Storage_DAS03/home3/menteeD/dna/WES_snakemake/KBPMA_WES-master/data/
# Name of reference FASTA (should be unzipped)
ref_fasta: Homo_sapiens.GRCh38.dna_sm.primary_assembly.fa
# Comma separated names of VCF files with known mutations. 
# Should all be in the reference directory
known_sites: dbsnp.vcf.gz, Homo_sapiens_assembly38.known_indels.vcf.gz, 1000G_phase1.snps.high_confidence.hg38.vcf.gz
# AF only VCF with common allele frequencies - use gnomAD file
germline_resource: /data/Storage_DAS03/home3/menteeD/dna/WES_snakemake/KBPMA_WES-master/data/gnomad_short.vcf.gz
# Biallelic variants only VCF with AF data - use EXAC file
contamination_resource: /data/Storage_DAS03/home3/menteeD/dna/WES_snakemake/KBPMA_WES-master/data/small_exac_common_3.hg38.vcf.gz

# GATK TMP directory
# Large files may overwhelm the default tmp directory (/tmp)
# Set this variable to an alternative filepath that has larger storage (ie $SCRATCH) if
# GATK is running out of storage during a run. Ideally this is fast storage
tmp_dir: /data/Storage_DAS03/home3/menteeD/dna/WES_snakemake/KBPMA_WES-master/data/tmp/


# Mutect2 Settings
# Number of Mutect2 workers per sample
num_workers: 20
# Variant calling without matched normal
# Only advised as a last resort - try to get matched normal samples
tumor_only: false
# Additional flags for Mutect2
mutect2_flags: None
# Additional flags for FilterMutectCalls
filter_flags: --min-reads-per-strand 1

# Panel of Normal (PON)
# Use PON with Mutect2 for variant calling
use_pon: true
# Filepath for PON. To create a new PON from all the normal samples, specify as None
pon_vcf: /data/Storage_DAS03/home3/menteeD/dna/WES_snakemake/KBPMA_WES-master/data/1000g_pon.hg38.vcf.gz


# Apply additional thresholds to filter variants
# When set to true, requires each SNV has a minimum of
# 15 reads covering the position and at least 5 reads
# with the mutant allele.
# When false, only use FilterMutectCalls criteria
stringent_filtering: false


# Annotation data sources
# Directory with VEP annotation data
vep_dir: /data/Storage_DAS03/home3/menteeD/dna/WES_snakemake/KBPMA_WES-master/data/VEP
# Assembly version name
assembly_version: GRCh38
# Value for Center field in the combined MAF
center_name: CPML
# Alternate Isoforms For vcf2maf Selection. Set as None to use Ensembl defaults
alternate_isoforms: None

## Singularity Containers
## This specifies the container to use for various steps in the pipeline
## The value can be any string (either local path or url) that can be queried using singularity pull
gatk_container: docker://tbencomo/gatk-bwa-samtools
multiqc_container: docker://ewels/multiqc:v1.11
mosdepth_container: docker://tbencomo/mosdepth
fastqc_container: docker://biocontainers/fastqc:v0.11.9_cv8
vep_container: docker://tbencomo/vep-vcf2maf

eda_container: docker://tbencomo/eda
